### ISSUE TITLE
GraphQL error: Cannot return full for non-nullable field VerifiableClaim.hash

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/daf-mobile#130]
I come to see the error immediately after entering a name in App.
Operating System: Linux Mint - Android device.

![image](https://user-images.githubusercontent.com/24407834/75043638-b2e49400-54c0-11ea-9707-0efd76092d86.png)

![image](https://user-images.githubusercontent.com/24407834/75043661-b9730b80-54c0-11ea-8965-5e6050ea6a8f.png)

![image](https://user-images.githubusercontent.com/24407834/75043677-be37bf80-54c0-11ea-94f9-1f17f25ba180.png)

**Comment by jasonhealy** [comment]
Thanks for reporting. 

Issue is related to #129
