### ISSUE TITLE
Error: React.Children.only expected to receive a single React element child

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/daf-mobile#131]
The error happens when clicking on any claim in the app
Operating System: Linux Mint - Android device

![image](https://user-images.githubusercontent.com/24407834/75043933-1373d100-54c1-11ea-9d6a-aeeca6c25666.png)

![image](https://user-images.githubusercontent.com/24407834/75043949-1969b200-54c1-11ea-88d0-29821195ffe4.png)

**Comment by jasonhealy** [comment]
@Muhammad-Altabba Thanks for reporting. We will look into it. In the meantime feel free to open a PR if you fix it before us.

**Comment by devrajsinghrawat** [comment]
Dear Team, 

I am getting similar error, attaching screenshots of error and my profile details if that helps to understand error better.. 

I am using app on Android and installed it using android studio on Mac


![Screenshot_20200226-104529_DafMobile](https://user-images.githubusercontent.com/44597990/75332957-901dfb00-5885-11ea-8308-47de6a8acb44.jpg)
![Screenshot_20200226-104609_DafMobile](https://user-images.githubusercontent.com/44597990/75332962-914f2800-5885-11ea-8b0b-4ffe750964ab.jpg)
![Screenshot_20200226-104640_DafMobile](https://user-images.githubusercontent.com/44597990/75332964-91e7be80-5885-11ea-96f2-1382b1b38abd.jpg)
![Screenshot_20200226-104633_DafMobile](https://user-images.githubusercontent.com/44597990/75332966-92805500-5885-11ea-95e8-8d2feabc9a08.jpg)
![Screenshot_20200226-103324_DafMobile](https://user-images.githubusercontent.com/44597990/75332971-9318eb80-5885-11ea-9067-8c2b50a31560.jpg)

**Comment by jasonhealy** [comment]
This is fixed by removing shared element transition
