### ISSUE TITLE
APK for android

### ISSUE THREAD

**Issue by HamzaBinSarfraz** [uport-project/daf-mobile#132]
Project is working on Emulator but I am unable to create APK 
Things i tried 

-  In my .env file 

```

ENV=dev

TGE_URI=https://custom.my-tgserver.com
TGE_WS_URI=wss://custom.my-tgserver.com

# Sentry configuration
SENTRY_DSN=dns
SENTRY_ENVIRONMENT=production
SENTRY_AUTH_TOKEN=authToken
SENTRY_ORG=orgName
SENTRY_PROJECT=daf-mobile
```

- for **codepush react native**

**created public key and deployment key usinf codePushCli and add them to android/app/build.gradle under buildTypes**

but every time ./gradlew buildRelease failed with this error 

> Task :app:compileReleaseJavaWithJavac FAILED

Any help for apk will be apprecited, thanks

**Comment by jasonhealy** [comment]
@HamzaBinSarfraz Can you try creating a free Sentry account and adding your configs? Codepush configs can be ignored and will be removed shortly. We are working on a default build flavour that skips Sentry upload as part of the build process.

**Comment by HamzaBinSarfraz** [comment]
@jasonhealy  i already added free Sentry account config in **.env**

**Comment by mirceanis** [comment]
@HamzaBinSarfraz can you share more details about the compilation error?

I get the error if I don't have any `BuildConfig.CODE_PUSH_*` properties defined for release but they go away after I define them. You can also use empty strings (like on `debug`)

```groovy
android {
   //...
    buildTypes {
        release {
            //...
            buildConfigField "String", "CODE_PUSH_ANDROID", '""'
            buildConfigField "String", "CODE_PUSH_PUBLIC_KEY", '""'
        }
    }
}
```

**Comment by HamzaBinSarfraz** [comment]
@mirceanis 

- my **android/app/build.gradle**

![](https://user-images.githubusercontent.com/30901435/75180681-86e63e80-575e-11ea-852a-baf99785955c.png)

- Screen Shot of error

![Screenshot from 2020-02-24 23-34-06](https://user-images.githubusercontent.com/30901435/75180821-c6ad2600-575e-11ea-9073-16a4305e0a6e.png)

**Comment by mirceanis** [comment]
@ HamzaBinSarfraz a quick workaround would be to copy those `buildConfigField`s to the `release` block as well

**Comment by jasonhealy** [comment]
@HamzaBinSarfraz I was able to reproduce this. Removing this this line and the app will build in release mode without any codepush configs.

https://github.com/uport-project/daf-mobile/blob/master/android/app/src/main/java/com/dafmobile/MainApplication.java#L37

**Comment by HamzaBinSarfraz** [comment]
> @HamzaBinSarfraz I was able to reproduce this. Removing this this line and the app will build in release mode without any codepush configs.
> 
> https://github.com/uport-project/daf-mobile/blob/master/android/app/src/main/java/com/dafmobile/MainApplication.java#L37

@jasonhealy it work thanks
