### ISSUE TITLE
Issues after scanning QR Code, error: Cannot Read Property 'Viewer' of undefined

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/daf-mobile#135]
Issues after scanning QR Code the following is presented on the mobile screen:
![Screenshot_20200226-131814_DafMobile](https://user-images.githubusercontent.com/24407834/75344559-24df2380-589b-11ea-9097-2e32f7129560.jpg)

Here is the details:
![Screenshot_20200226-131801_DafMobile](https://user-images.githubusercontent.com/24407834/75344563-26105080-589b-11ea-8294-2433299a466d.jpg)

![Screenshot_20200226-131807_DafMobile](https://user-images.githubusercontent.com/24407834/75344562-2577ba00-589b-11ea-9e19-3b18e81bc0ad.jpg)

**Comment by jasonhealy** [comment]
@Muhammad-Altabba Looks like there could be a race condition causing the the viewer to be undefined on Android. Does this occur only in dev mode on Android? 

The `viewer` query will be removed from the app soon and we will just query the current identity manually and manage `selectedIdentity` state in a global context. 

https://github.com/uport-project/daf-mobile/issues/115
