### ISSUE TITLE
Question: regarding Identity resolve, and profileImage

### ISSUE THREAD

**Issue by amarts** [uport-project/daf-mobile#150]
I was trying tomake some changes to self issuing credential, and when I added `profileImage` field with base64, in self issued credential, I could see that my local profile image got changed to that. Which is great :-)

Now, I wanted to check if I do the similar for issuing agent, would the agent's name (ie, shoetId) and profileImage would be resolved properly as Identity. Seems it doesn't. Any suggestion on how to get the agent's image and shortId resolved properly, so the display of credentials looks nice?

Not sure if question is clear, happy to provide info if one needs more details.

Thanks a lot for any hints.

**Comment by jasonhealy** [comment]
How are you ‘doing similar’ for the issuing agent?
If a credential about any identity is saved to the db then it becomes a known identity. If those credentials the contain profile fields that you mention they will be resolved by the framework.

**Comment by amarts** [comment]
I call `signVc()` just after `identityInit()` on agent (with signJwt()). Notice that the profileImage would be availble for local agent web after that, but not resolved by the mobile.

**Comment by jasonhealy** [comment]
Can you provide some code samples or a minimal repo of what you are trying to do?

**Comment by amarts** [comment]
Are you asking about mobile part or web app side?

On mobile part, I changed CreateFirstCredential to add a 'profileImage' as a field in VC. Which worked to get my profile image (through ViewerProfile) changed.


on agent side, something like this is what we are doing:

```
----
  const identity = await identityInit({
    name: eventsData[0].meta.name,
    profileImage: eventsData[0].meta.profileImage,
    url: eventsData[0].meta.url,
  })
  console.log("Issuer DID: ", identity.did)

----
async function identityInit(details: any) {
  await initializeDb()
  // Get or create new identity
  let identity: Daf.AbstractIdentity
  const identities = await core.identityManager.getIdentities()
  if (identities.length > 0) {
    identity = identities[0]
  } else {
    const identityProviders = await core.identityManager.getIdentityProviderTypes()
    identity = await core.identityManager.createIdentity(identityProviders[0].type)

    // Now issue a Profile credential
    await sendVc(identity.did, identity.did, 'self', details)
  }
  return identity
}

```

**Comment by jasonhealy** [comment]
Each instance of DAF is an agent. Each agent stores VCs from jwt messages in it's own db. 

1) Agent A can self sign a credential about itself or another Agent (name, profileImage) and share it with Agent B then both Agent **and** Agent B will have that credential saved and will be able to render it.

2) Agent B can self sign a credential about Agent A or another Agent and **NOT** share it. Agent B will have that data saved and will be able to render it but Agent A will not as it doesn't have the credentials saved.

If you want to show profile details for the WebAgent on mobile - the mobile needs to save a credential about the WebAgent. There are many ways to achieve this depending the overall structure of your app.

**Comment by amarts** [comment]
Thanks for this detail. 

We even thought of sharing the 'Identity' object in `from` field (thought we can pass a url there for icon), but currently only did string is allowed as of now. 

Will see how we can issue a credential to each agent from a central place, so each one gets a 'name' and profileImage' schemas. Will update here on what we come up with!

**Comment by jasonhealy** [comment]
We are actively working on improved profile information based on credentials in v4 of DAF. Our objective to is to provide the tools without being too opinionated in implementation and business logic. If you have any feedback or suggestions for specific use cases please reach out and share your thoughts and ideas!

**Comment by amarts** [comment]
Writing it here the things I think would be key for 'presentation' layer (whichever is on top of my head). Will send more usecases as a separate thread, or email.

We take the example of non-tech people as the end-users, mainly because in majority of the cases, they would be using the app (in whichever form) because the organisation has asked them to use it. 

When we scan for SDR, the Requests screen should clearly say who the request is coming from (things like icon/profileImage, name, at least, and can have url/short desc optionally).  This is helpful for an end-user who is using the App, because this is the place they are 'sharing' the information.

This won't hold good if mobile app is used for one org only! Then the source of the App itself is confirmation of issuer.

Another screen where we may need more details of issuers is a 'Credential' viewer, where we may give output with no details of raw/jwt/did but about just issuer detail, and fields (and time of issue).

**Comment by jasonhealy** [comment]
There is a number of ways that this public profile information can be shared - here are just a few of them that we have been discussing:

- Service Url in theDID doc pointing to a stored array of credentials. This would be easier for a web dids as it does not require gas to update the DID doc (Daf is currently working on better out of box did:web support).
- WalletConnect API could be changed to support credentials as part of it's `peerMeta` payload.

**Comment by amarts** [comment]
Ack! 

We are also thinking of having details of the 'registered' DIDs in our system in a DB, so our App can do a fetch if the details are missing.
