### ISSUE TITLE
Promise Rejection while submitting to Trust-Graph

### ISSUE THREAD

**Issue by amarts** [uport-project/daf-mobile#156]
Hi, I am aware project has moved over from trust-graph based connection to send and receive messages. While I am also in the process of validating wallectconnect and didcomm, looking for expert advise on what to look for:

My setup is, daf dependencies moved to 3.4.2, and TrustGraph still maintained in Provider.

The below error is happening when I try to do a 'CreateRequest'  -> 'SendRequest'.

The message says sent successfully to 'DID', but the logs say there is a Promise Rejection, and after this Every place just starts showing 'Error'.

```
Possible Unhandled Promise Rejection (id: 1):
Error: GraphQL error: Cannot return null for non-nullable field Identity.did.
```

I used to see similar issue just in basic SDR scanning from a Daf Agent earlier, but with 3.4.0 release, both on server and mobile, that had gone away.

Any possible advise would be appreciated!

**Comment by jasonhealy** [comment]
Can you try the same queries in the GQL playground of your daf version and update if that is working as expected for you?

**Comment by amarts** [comment]
Sure, let me try that!

**Comment by jasonhealy** [comment]
`npx daf graphql -p 8888`

**Comment by amarts** [comment]
Noticed that error was coming from querying local graphQL, not trust-agent: In Activity.tsx this is the error I get from lazyQuery... 

```json
{
  "graphQLErrors":[
                   {
                     "message":"Cannot return null for non-nullable field Identity.did.",
                     "locations":[],
                     "path":["viewer","messagesAll",0,"sdr",0,"iss",0,"did","did"]
                   },
                   {
                     "message":"Cannot return null for non-nullable field Identity.did.",
                     "locations":[],
                     "path":["viewer","messagesAll",0,"sdr",1,"iss",0,"did","did"]
                   }
                 ],
  "networkError": 'null'
}
```

**Comment by amarts** [comment]
Ok! Found the issue! it was my mistake... to make few flow changes, I added 'iss: [Identity]' as an option in 'fields' (for claims in CreateRequest), it seems graphQL didn't like that. `messageAll` and `sdr` structure helped to identify the issue!

Sorry about false alarm :D
