### ISSUE TITLE
Issue with missing 'vc' in sdr message (specially with <RequestItem />

### ISSUE THREAD

**Issue by amarts** [uport-project/daf-mobile#166]
I see that latest SDR response (from GET_MESSAGE_SDR), has some changes in format... but the fields sent to RequestItem needs a 'vc' (ie, credentails) field set.

Without a vc field being set, we can't set any fields in Response.

(Note this we tried with a SDR displayed with just the jwt (with an agent with daf-4.0)  and no walletconnect).

**Comment by amarts** [comment]
answering myself... I am seeing 'credentials' now, so would use that instead of vc... I used a version where selectiveDisclosure file had vc.

**Comment by jasonhealy** [comment]
yep, And you spotted that <RequestItem /> is now out of date too :)

uport-project/kancha-ui/issues/75

**Comment by jasonhealy** [comment]
Also, You can now pass a `replyUrl` in the SDR message and when responding we check if `walletConnect` is available and if not use the `replyUrl` and finally we check the DID doc.
