### ISSUE TITLE
Question: What is the best way to handle SDR without 'storing' it in DB

### ISSUE THREAD

**Issue by amarts** [uport-project/daf-mobile#172]
Hi,

we were thinking of handling SDR flow directly with the daf web agent, without WalletConnect, and wanted it to be mostly for only 'login' like feature, so instead of having 'Later' option, it will be 'Share' or Ignore.

Now, the challenge I am facing is, I am not able to get JWT decoded without doing a NEW_MESSAGE! Is there any suggestions to decode JWT from SDR without storing  it in DB?

**Comment by simonas-notcat** [comment]
Hey @amarts , `handleMessage` method has an optional parameter `save`, which is `true` by default. Set it to false, and it will not be saved in the DB

https://github.com/uport-project/daf/blob/master/docs/Docs.md#typescript-4

**Comment by amarts** [comment]
Thanks :-) remember seeing this, but couldn't map it right!
