### ISSUE TITLE
WalletConnect doesn't work well with dafhub

### ISSUE THREAD

**Issue by ilovelili** [uport-project/daf-mobile#191]
**Describe the issue**
I scan the QR code from dafhub(`https://dafhub.herokuapp.com/login`) while nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Access dafhub, click 'connect', then QR code shows
2. Open daf-mobile app, tap the scanner icon, camera starts up then scan the QR code
3. Camera will close automatically after scanning however nothing happens on dafhub side.

**Expected behaviour**
Dafhub show show dashboard page after QR code scanned by daf-mobile

**Device info (please complete the following information):**
 - Device: [HuaWei HW608]
 - OS Version: [Android 7.0]

**Daf info (please complete the following information):**
 - Daf Mobile Version [1.38.0]
 - Daf Version [5.6.5]

**Additional context**
I scan dafhub using trust wallet while it works well

**Comment by jasonhealy** [comment]
You should get a request in the mobile app after scanning the QR.

Can you follow the code from here to see if the request screen is being blocked from showing?

https://github.com/uport-project/daf-mobile/blob/master/src/components/WalletConnect.tsx#L19

**Comment by ilovelili** [comment]
Hi Jason!

Thank you very much for your quick reply!

I added some debug outputs and found the event registry seems to be good.

```
const debug = Debug("daf-component:wallet-connect");

useEffect(() => {
    wcEventHub.addListener(
      AppConstants.events.WALLET_CONNECT.SESSION_REQUEST_INT,
      async ({ peerId, peerMeta, payload }: any) => {
        const requestType = AppConstants.requests.SESSION;

        navigate(Screens.Requests.screen, {
          requestType,
          peerId,
          peerMeta,
          payload
        });
      }
    );

    debug(`event is ${wcEventHub.eventNames().join("|")}`); // Add if event has been added to wcEventHub

	...

```

The terminal output is ```daf-component:wallet-connect event is session_request_internal +0ms```

Then I checked if anything wrong with WalletConnect provider(`https://github.com/uport-project/daf-mobile/blob/master/src/providers/WalletConnect.tsx#L74`). I added a debug log to catch the init error

```
 const walletConnectInit = async () => {
    try {
      const sessions = await asyncStorageLoadSessions()
      const _connectors = await Promise.all(
        Object.values(sessions).map(async session => {
          const nativeOptions = await getNativeOptions()
          return new WalletConnect({ session }, nativeOptions)
        }),
      )

      updateConnectors(_connectors)
    } catch (error) {
      debug(`walletconnect init error`);
      debug(error);
    }
  }
```

It looks like init failed since the output is 
```daf-provider:wallet-connect walletconnect init error +210ms```

The error output is 
```daf-provider:wallet-connect values@[native code]
walletConnectInit$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:337020:74
........ (skip the stack trace info here)
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:7953:15
flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:7755:21
flushedQueue@[native code]

invokeCallbackAndReturnFlushedQueue@[native code] +1ms
```

I also added debug log in `walletConnectOnSessionRequest`(`https://github.com/uport-project/daf-mobile/blob/master/src/providers/WalletConnect.tsx#L91`) which is called from UI to establish a connection

```
const walletConnectOnSessionRequest = async (uri: string) => {
    debug("onSessionRequest");
    const nativeOptions = await getNativeOptions();

    // the output here is 
    // daf-provider:wallet-connect uri is wc:083a8046-196b-4c22-8fac-2be933ad27a6@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=427498220a3fc41219d375110bb4b4b3d2d03c2373a0a418aaa367dea57576f9 +144ms
    debug(`uri is ${uri}`);
	
    const connector = new WalletConnect({ uri }, nativeOptions);
    
    // then I check if connector is connected, it returns false
    // daf-provider:wallet-connect connected: false +5ms
    debug(`connected: ${connector.connected}`);
	
    // I tried to connect it... unluckily it doesn't work
	
    if (!connector.connected) {
      await connector.createSession();
    }
    // it still remains unconnected
	
    ...

```

Do you think the error happens on wallectconnect init step? If so, did I miss some extra walletconnect configs somewhere? Thank you!

Min

**Comment by ilovelili** [comment]
It seems `const sessions = await asyncStorageLoadSessions();` in `walletConnectInit` is returning empty and causing init error. I got error log like ```AsyncStorage: value does not exist for key: walletConnect```

**Comment by jasonhealy** [comment]
sessions would be empty if you have never connected, that just checks for previously connections and reconnects to them. After `SESSION_REQUEST_INT` fires it should open a new view - is that view opening? 

` ...
navigate(Screens.Requests.screen, {
          requestType,
          peerId,
          peerMeta,
          payload
 });
...
`

**Comment by ilovelili** [comment]
No. The view is not opening. After QR code scanned, the camera got closed (which is expected behavior) and nothing happens. Nothing changes on dafhub side either.

I understand session can be empty and it shouldn't be the main problem. But my `SESSION_REQUEST` event is never triggered after QR code scanned, which will emit `SESSION_REQUEST_INT` and open a new view.

**Comment by ilovelili** [comment]
But if it only happens on my side, then please don't be worried about that.. I just want to double check if it's only my problem or not. Maybe there is some local environment issue

**Comment by jasonhealy** [comment]
This could be related to Android. I can check later.

**Comment by ilovelili** [comment]
Thank you very much sir!

**Comment by ilovelili** [comment]
It works with my iPhone. I am going to close it now. Thank you!
